### ISSUE TITLE
Inference on CPU

### ISSUE THREAD

**Issue by vikrant7** [luminxu/ViPNAS#7]
Hi,
I want to run ViPNAS on the CPU. For that, I used webcam_demo.py of mmpose (https://github.com/open-mmlab/mmpose/blob/master/demo/webcam_demo.py). But, I am getting only 3fps for S-ViPNAS-ResNet50. 

Please guide me to achieve the same inference time as reported in the paper i.e. 25fps on the single-core CPU.

**Comment by luminxu** [comment]
The [webcam demo](https://github.com/open-mmlab/mmpose/blob/master/demo/webcam_demo.py) tool in mmpose integrates the human detector and the pose estimator. It first detects all the persons in the image using a human detection model, then applies a pose estimation model (S-ViPNAS-ResNet50 in your implementation) to process each person one by one, which leads to the low fps performance. 

You should input the cropped images and test the model inference time of S-ViPNAS-ResNet50 to obtain the runtime performance. The same cpu as reported in the paper is recommended in order to get the same runtime performance. Hope you could enjoy our proposed ViPNAS :).
